FROM golang:1.20-alpine3.16 as builder

RUN apk update && apk add --no-cache bash

WORKDIR /go/src/github.com/argoproj/argo-workflows
COPY go.mod .
COPY go.sum .
RUN --mount=type=cache,target=/go/pkg/mod go mod download

COPY . .
